name = "AskTellOptimization"
uuid = "1b97551c-c9b4-4b74-b716-a03fb36d7b8d"
authors = ["Samuel Belko <samuelbelko@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"

[compat]
CommonSolve = "0.2.4"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
